### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by hannanmustajab** [MattFlood7/LinkedInBot#9]
I am getting this error again and again. Can you help me fix this ? 
Thanks !
Traceback (most recent call last):
  File "/Users/abdulhannanmustajab/Downloads/python-linkedin-bot-master/newbot/LinkedInBot/LinkedInBot.py", line 421, in <module>
    Launch()
  File "/Users/abdulhannanmustajab/Downloads/python-linkedin-bot-master/newbot/LinkedInBot/LinkedInBot.py", line 42, in Launch
    StartBrowser(1)
  File "/Users/abdulhannanmustajab/Downloads/python-linkedin-bot-master/newbot/LinkedInBot/LinkedInBot.py", line 82, in StartBrowser
    LinkedInBot(browser)
  File "/Users/abdulhannanmustajab/Downloads/python-linkedin-bot-master/newbot/LinkedInBot/LinkedInBot.py", line 148, in LinkedInBot
    browserTitle = (browser.title).encode('ascii', 'ignore').replace('  ',' ')
TypeError: a bytes-like object is required, not 'str'

**Comment by aferreira44** [comment]
I think my PR #11 solves this error. Could you test it, please?

https://github.com/aferreira44/LinkedInBot

PS: It will run only on Python 3.x

**Comment by cris006** [comment]
> I think my PR #11 solves this error. Could you test it, please?
> 
> https://github.com/aferreira44/LinkedInBot
> 
> PS: It will run only on Python 3.x

This fixed the error at visitedUsersFile.write(str(profileID)+'\r\n')  but it still occurs at browserTitle

**Comment by cris006** [comment]
> > I think my PR #11 solves this error. Could you test it, please?
> > https://github.com/aferreira44/LinkedInBot
> > PS: It will run only on Python 3.x
> 
> This fixed the error at visitedUsersFile.write(str(profileID)+'\r\n') but it still occurs at browserTitle

It works now, found your other changes required, adding b'' in subsequent string calls
